import React from "react"
import Navbar from "../../Component/Navbar";
import Footer from "../../Component/Footer";

export const metadata = {
  title: "StatsPage",
  description: "Generated by create next app",
};

const StatsPage = () => {
    return(
        <div>
            
        </div>
    )
}

export default StatsPage