
export const metadata = {
  title: "Stat page",
  description: "Generated by create next app",
};

import StatsClient from "./StatsClient";

export default function StatsPage() {
    return <StatsClient />;
}