import Navbar from "../../Component/Navbar";
import Footer from "../../Component/Footer";
import React from "react";

export const metadata = {
  title: "TimelinePage",
  description: "Generated by create next app",
};

const TimelinePage = () => {
    return(
        <div>
            
        </div>
    )
}

export default TimelinePage;