import React from "react";
import TimelineClient from "./TimelineClient";

export const metadata = {
  title: "Timeline Page",
  description: "Generated by create next app",
};

export default function TimelinePage() {
    return <TimelineClient />;
}
